routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Route::get('/', [ 'as'=> 'home', 'uses'=> 'PageController@home']);
Route::get('/about', [ 'as'=> 'about', 'uses'=> 'PageController@about']);
Route::get('/products', [ 'as'=> 'products', 'uses'=> 'PageController@products']);
Route::get('/products/{product}', [ 'as'=> 'products.show', 'uses'=> 'PageController@showProducts']);
Route::get('/my-account', [ 'as'=> 'my-account', 'uses'=> 'PageController@myAccount']);
Route::post('user/login', [ 'as'=> 'user.login', 'uses'=> 'UserController@login']);
Route::post('user/store', [ 'as'=> 'user.store', 'uses'=> 'UserController@store']);
Route::put('/user/{user}', [ 'as'=> 'user.update', 'uses'=> 'UserController@update']);
Route::put('/updatepass/{id}', [ 'as'=> 'user.updatepass', 'uses'=> 'UserController@updatePassword']);
Route::post('/checkmail', [ 'as'=> 'checkmail', 'uses'=> 'UserController@checkmail']);
Route::get('user/logout', [ 'as'=> 'user.logout', 'uses'=> 'UserController@logout']);
Route::get('register/verify/{token}', ['as' => 'confirm_email', 'uses' => 'UserController@confirmMail']);
Route::get('/search', [ 'as'=> 'products.search', 'uses'=> 'ProductController@search']);
Route::post('/filterproducts', ['as'=>'products_filter.loadAjax','uses'=>'ProductController@filterProducts']);
Route::post('/getproducts', ['as'=>'products.loadAjax','uses'=>'ProductController@loadProducts']);
Route::get('/add-to-cart/{id}', ['as' => 'products.addToCart', 'uses' => 'ProductController@getAddToCart']);
Route::get('/cart', ['as' => 'products.cart', 'uses' => 'ProductController@showCart']);
Route::get('/get-cart', ['as' => 'products.getCart', 'uses' => 'ProductController@getCart']);
Route::get('/remove-cart/{slug}', ['as' => 'products.deleteFromCart', 'uses' => 'ProductController@deleteFromCart']);
Route::get('/checkout', ['as' => 'products.checkout', 'uses' => 'ProductController@checkout']);
Route::post('/checkout', ['as' => 'products.postCheckout', 'uses' => 'ProductController@postCheckout']);
Route::get('/order-complete/{token}', ['as' => 'products.orderSuccess', 'uses' => 'ProductController@orderSuccess']);
Route::post('/orders/customer', ['as' => 'orders.storeOrderCustomer', 'uses' => 'OrderController@storeOrderCustomer']);
Route::get('auth/{provider}', 'AuthController@redirectToProvider');
Route::get('auth/{provider}/callback', 'AuthController@handleProviderCallback');
Route::get('/order-details/{id}','OrderController@orderDetails');
Route::group(['middleware' => ['checkifadmin'] , 'prefix' => 'admin'], function () {
	Route::get('dashboard', [ 'as'=> 'admin.dashboard', 'uses'=> 'PageController@dashboard']);
	Route::resource('users','UserController');
	Route::resource('categories','CategoryController');
	Route::resource('products','ProductController');
	Route::resource('orders','OrderController');
	Route::resource('tasks','TaskController');
	Route::resource('drivers','DriverController');
});
Route::group(['middleware' => ['checkifadmin']], function () {

});

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
  @include('partials.admin.meta')
  @include('partials.admin.styles') 
  @include('partials.admin.polyfills')
  </head>
  <body>
    <div class="be-wrapper">
      <nav class="navbar navbar-default navbar-fixed-top be-top-header">
        <div class="container-fluid">
          <div class="be-right-navbar">
            <ul class="nav navbar-nav navbar-right be-user-nav">
              <li class="dropdown"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle">
              {{ HTML::image('admin/assets/img/avatar.png', 'Avatar') }}<span class="user-name">{{Auth::user()->firstname}} {{Auth::user()->lastname}}</span></a>
                <ul role="menu" class="dropdown-menu">
                  <li>
                    <div class="user-info">
                      <div class="user-name">{{Auth::user()->firstname}} {{Auth::user()->lastname}}</div>
                    </div>
                  </li>
                  {{-- <li><a href="#"><span class="icon mdi mdi-face"></span> Account</a></li>
                  <li><a href="#"><span class="icon mdi mdi-settings"></span> Settings</a></li> --}}
                  <li><a href="{{URL::route('user.logout')}}"><span class="icon mdi mdi-power"></span> Logout</a></li>
                </ul>
              </li>
            </ul>
            <div class="page-title"><span>Order420</span></div>
            <ul class="nav navbar-nav navbar-right be-icons-nav">
              <li class="dropdown"><a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="dropdown-toggle"><span class="icon mdi mdi-notifications"></span><span class="indicator"></span></a>
                <ul class="dropdown-menu be-notifications">
                  <li>
                    <div class="title">Notifications<span class="badge">3</span></div>
                    <div class="list">
                      <div class="be-scroller">
                        <div class="content">
                          <ul>
                            <li class="notification notification-unread"><a href="#">
                                <div class="image">
                                {{ HTML::image('admin/assets/img/avatar2.png', 'Avatar 2') }}
                                </div>
                                <div class="notification-info">
                                  <div class="text"><span class="user-name">Jessica Caruso</span> accepted your invitation to join the team.</div><span class="date">2 min ago</span>
                                </div></a></li>
                            <li class="notification"><a href="#">
                                <div class="image">
                                {{ HTML::image('admin/assets/img/avatar3.png', 'Avatar 3') }}
                                </div>
                                <div class="notification-info">
                                  <div class="text"><span class="user-name">Joel King</span> is now following you</div><span class="date">2 days ago</span>
                                </div></a></li>
                            <li class="notification"><a href="#">
                                <div class="image">
                                {{ HTML::image('admin/assets/img/avatar4.png', 'Avatar 4') }}
                                </div>
                                <div class="notification-info">
                                  <div class="text"><span class="user-name">John Doe</span> is watching your main repository</div><span class="date">2 days ago</span>
                                </div></a></li>
                            <li class="notification"><a href="#">
                                <div class="image">
                                {{ HTML::image('admin/assets/img/avatar5.png', 'Avatar 5') }}
                                </div>
                                <div class="notification-info"><span class="text"><span class="user-name">Emily Carter</span> is now following you</span><span class="date">5 days ago</span></div></a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div class="footer"> <a href="#">View all notifications</a></div>
                  </li>
                </ul>
              </li>
          </div>
        </div>
      </nav>
      <div class="be-left-sidebar">
        <div class="left-sidebar-wrapper"><a href="#" class="left-sidebar-toggle">@yield('page-title')</a>
          <div class="left-sidebar-spacer">
            <div class="left-sidebar-scroll">
              <div class="left-sidebar-content">
                <ul class="sidebar-elements">
                  <li class="divider">Menu</li>
                  <li><a href="{{URL::route('admin.dashboard')}}"><i class="icon mdi mdi-home"></i><span>Dashboard</span></a></li>
                  <li><a href="{{URL::route('users.index')}}"><i class="icon mdi mdi-account"></i><span>User Management</span></a></li>
                  <li><a href="{{URL::route('products.index')}}"><i class="icon mdi mdi-shopping-basket"></i><span>Products</span></a>
                  </li>
                  <li><a href="{{URL::route('categories.index')}}"><i class="icon mdi mdi-tag"></i><span>Categories</span></a>
                  </li>
                  <li><a href="{{URL::route('orders.index')}}"><i class="icon mdi mdi-shopping-cart"></i><span>Orders</span></a>
                  </li>
                  <li><a href="{{URL::route('tasks.index')}}"><i class="icon mdi mdi-shopping-cart"></i><span>Delivery Tasks</span></a>
                  </li>
                  <li><a href="{{URL::route('drivers.index')}}"><i class="icon mdi mdi-bike"></i><span>Drivers</span></a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="be-content">
        <div class="page-head">
          <h2 class="page-head-title">@yield('page-title')</h2>
          <ol class="breadcrumb page-head-nav">
            <li><a href="{{URL::route('admin.dashboard')}}">Home</a></li>
            <li class="active">@yield('page-title')</li>
          </ol>
        </div>
        <div class="main-content container-fluid">
          @yield('page-content')
        </div>
      </div>
    </div>
    @include('partials.admin.scripts')    
  </body>
</html>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<!--[if IE 9]><html class="ie ie9"><![endif]-->
<html>
<head>
@include('partials.site.meta')
@include('partials.site.styles') 
@include('partials.site.polyfills')
</head>
<body>
    <!--[if lte IE 8]>
        <p class="chromeframe">You are using an <strong>outdated</strong> browser. 
        Please <a href="http://browsehappy.com/">upgrade your browser</a>.</p>
    <![endif]-->
    <header>
        <div class="container-fluid">
            <div class="row">
                <div class="col--md-4 col-sm-4 col-xs-4">
                    <a href="/" id="logo" >
                        {{ Html::image('site/img/logo_order420.png', '', array('class' => 'hidden-xs' , 'data-retina' => 'true',  'width' => '100' , 'height' =>'23' )) }}
                        {{ Html::image('site/img/logo_order420.png', '', array('class' => 'hidden-lg hidden-md hidden-sm' , 'data-retina' => 'true', 'width' => '100' , 'height' =>'23' )) }}
                    </a>
                </div>
                <nav class="col--md-8 col-sm-8 col-xs-8">
                    <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
                    <a href="/cart" class="mbl-cart"><i class="icon_cart_alt"></i><span class="cartCount badge">{{ Session::has('cart') ? Session::get('cart')->totalQty : null }}</span></a>
                    <div class="main-menu">
                        <div id="header_menu">
                            {{ Html::image('site/img/logo_order420.png', '', array('data-retina' => 'true',  'width' => '100' , 'height' =>'23' )) }}
                        </div>
                        <a href="#" class="open_close" id="close_in"><i class="icon_close"></i></a>
                        <ul>
                            <li><a href="/">Home</a></li>
                            <li><a href="/about">About</a></li>
                            <li><a href="/products">Products</a></li>
                            @if (Auth::check())
                            <li><a href="/my-account">My Account</a></li>
                            <li><a href="{{URL::route('user.logout')}}">Log Out</a></li>
                            @else
                                <li><a href="#0" data-toggle="modal" data-target="#login">Login</a></li>
                                <li><a href="#0" data-toggle="modal" data-target="#register">Register</a></li>
                                
                            @endif
                            <li class="submenu-cart">
                                <a href="/cart" class="show-submenu"><i class="icon_cart_alt"></i><span class="cartCount badge">{{ Session::has('cart') ? Session::get('cart')->totalQty : null }}</span></a>
                                <ul>
                                    <li class="cartItems">
                                    <p style="margin: 0px"></p>
                                    <table class="table table_summary cart_table">
                                        <tbody class="cart-widget">
                                        </tbody>
                                    </table>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    @yield('content')
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-3">
                    <h3>Secure payments with</h3>
                    <p>
                        {{ Html::image('site/img/cards.png', '', array('class' => 'img-responsive')) }}
                    </p>
                </div>
                <div class="col-md-3 col-sm-3">
                    <h3>About</h3>
                    <ul>
                        <li><a href="/about">About us</a></li>
                        <li><a href="/faq">Faq</a></li>
                        <li><a href="/contacts">Contacts</a></li>
                        <li><a href="/terms">Terms and conditions</a></li>
                    </ul>
                </div>
                <div class="col-md-5 col-sm-6" id="newsletter">
                    <h3>Newsletter</h3>
                    <p>
                        Join our newsletter to keep be informed about offers and news.
                    </p>
                    <div id="message-newsletter_2">
                    </div>
                    <form method="post" action="assets/newsletter.php" name="newsletter_2" id="newsletter_2">
                        <div class="form-group">
                            <input name="email_newsletter_2" id="email_newsletter_2" type="email" value="" placeholder="Your mail" class="form-control">
                        </div>
                        <input type="submit" value="Subscribe" class="btn_1" id="submit-newsletter_2">
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div id="social_footer">
                        <ul>
                            <li><a href="#0"><i class="icon-facebook"></i></a></li>
                            <li><a href="#0"><i class="icon-twitter"></i></a></li>
                            <li><a href="#0"><i class="icon-google"></i></a></li>
                            <li><a href="#0"><i class="icon-instagram"></i></a></li>
                            <li><a href="#0"><i class="icon-pinterest"></i></a></li>
                            <li><a href="#0"><i class="icon-vimeo"></i></a></li>
                            <li><a href="#0"><i class="icon-youtube-play"></i></a></li>
                        </ul>
                        <p>© Order420 2017</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    @include('partials.site.loginForm')
    @include('partials.site.registerForm')
    @include('partials.site.scripts')
</body>
</html>